### ISSUE TITLE
 Run Error

### ISSUE THREAD

**Issue by cat12385** [largelymfs/paragraph2vec#1]
Hi:
 When I run "python test.py training_text testing_text" ，Such errors occur：

```
WRONG PLACE
   Exception in thread Thread-24:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "test.py", line 271, in worker_train
    job_words = sum(train_sentence(self, sentence[0],sentence[1], alpha, work, neu1) for sentence     in job)
  File "test.py", line 271, in <genexpr>
    job_words = sum(train_sentence(self, sentence[0],sentence[1], alpha, work, neu1) for sentence in job)
  File "test.py", line 17, in train_sentence
   if window!=0:
NameError: global name 'window' is not defined
```

Please tell me how to solve it，thanks!

**Comment by andyyuan78** [comment]
where is the file training_text & testing_text?
#2 opened just now by andyyuan78

**Comment by largelymfs** [comment]
Training_text and Testing_Text are the training and testing dataset. Each line is a `document` described in the paper.
